// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web options — FlutterFire loads the matching Firebase JS SDK itself.
  /// Do not add firebase-*-compat.js scripts to `web/index.html`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrlxFO3urhXWymVaDn6FS3cxdth84kxM',
    appId: '1:307616113629:web:26333d6418aa2bdda20c34',
    messagingSenderId: '307616113629',
    projectId: 'aunty-b7c60',
    authDomain: 'aunty-b7c60.firebaseapp.com',
    storageBucket: 'aunty-b7c60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEEpdPxQ1qs1WAHEsArMma22qYPaPQX1U',
    appId: '1:307616113629:android:db7bae002953eb27a20c34',
    messagingSenderId: '307616113629',
    projectId: 'aunty-b7c60',
    storageBucket: 'aunty-b7c60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAgunehd58EeqZSqlu_7Pofi00PCOPB3A',
    appId: '1:307616113629:ios:9e607f7702176f2fa20c34',
    messagingSenderId: '307616113629',
    projectId: 'aunty-b7c60',
    storageBucket: 'aunty-b7c60.firebasestorage.app',
    iosBundleId: 'com.example.aunty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAgunehd58EeqZSqlu_7Pofi00PCOPB3A',
    appId: '1:307616113629:ios:9e607f7702176f2fa20c34',
    messagingSenderId: '307616113629',
    projectId: 'aunty-b7c60',
    storageBucket: 'aunty-b7c60.firebasestorage.app',
    iosBundleId: 'com.example.aunty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANrlxFO3urhXWymVaDn6FS3cxdth84kxM',
    appId: '1:307616113629:web:26333d6418aa2bdda20c34',
    messagingSenderId: '307616113629',
    projectId: 'aunty-b7c60',
    authDomain: 'aunty-b7c60.firebaseapp.com',
    storageBucket: 'aunty-b7c60.firebasestorage.app',
  );
}
